name:                lh-tutorial
version:             0.1.0.0
license:             BSD3

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- vector

library:
  source-dirs: src
